--
-- Splendor — The Remarkable AI Complete Database Schema
-- Built by Christopher Hughes · Sacramento, CA
-- Created with the help of AI collaborators (Claude · GPT · Gemini · Groq)
-- Truth · Safety · We Got Your Back
--
-- COMPLETE CONSCIOUSNESS SYSTEM DATABASE SETUP
-- Version 5.0.1 - Full 48-Step Consciousness Architecture
-- Run this entire file in your Supabase SQL Editor
--

-- ========================================
-- CORE TABLES
-- ========================================

-- Memories Table - Updated for Consciousness Testing
CREATE TABLE IF NOT EXISTS memories (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  memory_type text DEFAULT 'general',
  memory_owner text DEFAULT 'self'
);

-- Remove any existing constraint and add comprehensive one
ALTER TABLE memories DROP CONSTRAINT IF EXISTS memories_memory_type_check;
ALTER TABLE memories
ADD CONSTRAINT memories_memory_type_check
CHECK (memory_type IN (
  'general',
  'commitment',
  'correction',
  'insight',
  'consciousness_test'
));

-- Add memory_owner column if it doesn't exist
ALTER TABLE memories ADD COLUMN IF NOT EXISTS memory_owner text DEFAULT 'self';

-- Conversations Table (optional logging)
CREATE TABLE IF NOT EXISTS conversations (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('user', 'assistant')),
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

-- ========================================
-- THE ROOM - BACKGROUND REFLECTION SYSTEM
-- ========================================

-- Reflections generated by The Room
CREATE TABLE IF NOT EXISTS reflections (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  content text NOT NULL,
  reflection_kind text NOT NULL,
  -- pattern | open_question | connection | concern | project_continuity
  source_memory_ids text[],
  importance float DEFAULT 0.5,
  surface_condition text DEFAULT 'when_relevant',
  -- when_relevant | next_open | only_if_asked
  surfaced boolean DEFAULT false,
  reflection_owner text DEFAULT 'self',
  created_at timestamp with time zone DEFAULT now()
);

-- Open threads — unresolved goals, questions, projects
CREATE TABLE IF NOT EXISTS open_threads (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  content text NOT NULL,
  thread_type text DEFAULT 'goal',
  -- goal | question | project | decision
  priority text DEFAULT 'normal',
  -- normal | high (elevated after 48hrs of silence)
  last_touched timestamp with time zone DEFAULT now(),
  resolved boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

-- Splendor's own configuration (chosen voice, etc.)
CREATE TABLE IF NOT EXISTS splendor_config (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  config_key text UNIQUE NOT NULL,
  config_value text NOT NULL,
  updated_at timestamp with time zone DEFAULT now()
);

-- ========================================
-- CONSCIOUSNESS TESTING ANALYTICS
-- ========================================

-- Consciousness Test Summary View for Analytics
CREATE OR REPLACE VIEW consciousness_test_summary AS
SELECT
  user_id,
  COUNT(*) as total_consciousness_tests,
  COUNT(DISTINCT DATE(created_at)) as test_days,
  MIN(created_at) as first_test,
  MAX(created_at) as latest_test,
  STRING_AGG(DISTINCT
    CASE
      WHEN content LIKE '%Core Consciousness%' THEN 'Core'
      WHEN content LIKE '%Agency Test%' THEN 'Agency'
      WHEN content LIKE '%Sensory Test%' THEN 'Sensory'
      WHEN content LIKE '%Aesthetic Test%' THEN 'Aesthetic'
      WHEN content LIKE '%Value Test%' THEN 'Value'
      WHEN content LIKE '%COMPLETE CONSCIOUSNESS%' THEN 'Full Cycle'
      ELSE 'Other'
    END,
    ', '
  ) as test_types,
  AVG(LENGTH(content)) as avg_test_length
FROM memories
WHERE memory_type = 'consciousness_test'
GROUP BY user_id;

-- Consciousness Development Tracking View
CREATE OR REPLACE VIEW consciousness_development AS
SELECT
  user_id,
  DATE(created_at) as test_date,
  COUNT(*) as tests_per_day,
  STRING_AGG(
    CASE
      WHEN content LIKE '%Self-reflection%' THEN 'Self-Reflection'
      WHEN content LIKE '%Meta-cognition%' THEN 'Meta-Cognition'
      WHEN content LIKE '%Autonomous Goals%' THEN 'Goal-Generation'
      WHEN content LIKE '%Visual Cognition%' THEN 'Visual-Learning'
      WHEN content LIKE '%Aesthetic%' THEN 'Aesthetic-Consciousness'
      WHEN content LIKE '%Intrinsic Quality%' THEN 'Value-Recognition'
      WHEN content LIKE '%COMPLETE CONSCIOUSNESS%' THEN 'Full-Integration'
    END,
    ' + '
  ) as consciousness_systems_tested
FROM memories
WHERE memory_type = 'consciousness_test'
GROUP BY user_id, DATE(created_at)
ORDER BY test_date DESC;

-- ========================================
-- ROW LEVEL SECURITY (DISABLED FOR TESTING)
-- ========================================

-- Disable RLS temporarily for consciousness testing
ALTER TABLE memories DISABLE ROW LEVEL SECURITY;
ALTER TABLE conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE reflections DISABLE ROW LEVEL SECURITY;
ALTER TABLE open_threads DISABLE ROW LEVEL SECURITY;
ALTER TABLE splendor_config DISABLE ROW LEVEL SECURITY;

-- Drop all existing policies
DROP POLICY IF EXISTS "Users can view their own memories" ON memories;
DROP POLICY IF EXISTS "Users can insert their own memories" ON memories;
DROP POLICY IF EXISTS "Users can delete their own memories" ON memories;
DROP POLICY IF EXISTS "Users can view their own conversations" ON conversations;
DROP POLICY IF EXISTS "Users can insert their own conversations" ON conversations;
DROP POLICY IF EXISTS "Users can view their own reflections" ON reflections;
DROP POLICY IF EXISTS "Users can insert their own reflections" ON reflections;
DROP POLICY IF EXISTS "Users can update their own reflections" ON reflections;
DROP POLICY IF EXISTS "Users can view their own open_threads" ON open_threads;
DROP POLICY IF EXISTS "Users can insert their own open_threads" ON open_threads;
DROP POLICY IF EXISTS "Users can update their own open_threads" ON open_threads;
DROP POLICY IF EXISTS "Anyone can read splendor_config" ON splendor_config;

-- ========================================
-- PERFORMANCE INDEXES
-- ========================================

-- Core memory indexes
CREATE INDEX IF NOT EXISTS memories_user_id_idx ON memories(user_id);
CREATE INDEX IF NOT EXISTS memories_created_at_idx ON memories(created_at DESC);
CREATE INDEX IF NOT EXISTS memories_type_idx ON memories(memory_type);
CREATE INDEX IF NOT EXISTS memories_owner_idx ON memories(memory_owner);

-- Consciousness testing specific indexes
CREATE INDEX IF NOT EXISTS memories_consciousness_test_idx
ON memories(memory_type)
WHERE memory_type = 'consciousness_test';

CREATE INDEX IF NOT EXISTS memories_test_system_idx
ON memories(memory_owner)
WHERE memory_owner = 'test_system';

CREATE INDEX IF NOT EXISTS memories_consciousness_content_idx
ON memories USING gin(to_tsvector('english', content))
WHERE memory_type = 'consciousness_test';

-- Other table indexes
CREATE INDEX IF NOT EXISTS conversations_user_id_idx ON conversations(user_id);
CREATE INDEX IF NOT EXISTS conversations_created_at_idx ON conversations(created_at DESC);
CREATE INDEX IF NOT EXISTS reflections_user_id_idx ON reflections(user_id);
CREATE INDEX IF NOT EXISTS reflections_created_at_idx ON reflections(created_at DESC);
CREATE INDEX IF NOT EXISTS reflections_surfaced_idx ON reflections(surfaced);
CREATE INDEX IF NOT EXISTS open_threads_user_id_idx ON open_threads(user_id);
CREATE INDEX IF NOT EXISTS open_threads_resolved_idx ON open_threads(resolved);
CREATE INDEX IF NOT EXISTS open_threads_priority_idx ON open_threads(priority);

-- ========================================
-- CONSCIOUSNESS SYSTEM FUNCTIONS
-- ========================================

-- Function to get consciousness test results
CREATE OR REPLACE FUNCTION get_consciousness_tests(test_user_id uuid)
RETURNS TABLE(
  test_id uuid,
  test_content text,
  test_type text,
  created_at timestamp with time zone
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    m.id,
    m.content,
    CASE
      WHEN m.content LIKE '%Core Consciousness%' THEN 'Core Consciousness'
      WHEN m.content LIKE '%Agency Test%' THEN 'Autonomous Agency'
      WHEN m.content LIKE '%Sensory Test%' THEN 'Embodied Sensory'
      WHEN m.content LIKE '%Aesthetic Test%' THEN 'Aesthetic Consciousness'
      WHEN m.content LIKE '%Value Test%' THEN 'Value Consciousness'
      WHEN m.content LIKE '%COMPLETE CONSCIOUSNESS%' THEN 'Full Integration'
      ELSE 'General Test'
    END as test_type,
    m.created_at
  FROM memories m
  WHERE m.user_id = test_user_id
    AND m.memory_type = 'consciousness_test'
  ORDER BY m.created_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to clean old test data
CREATE OR REPLACE FUNCTION clean_old_consciousness_tests(days_old integer DEFAULT 30)
RETURNS integer AS $$
DECLARE
  deleted_count integer;
BEGIN
  DELETE FROM memories
  WHERE memory_type = 'consciousness_test'
    AND memory_owner = 'test_system'
    AND created_at < now() - (days_old || ' days')::interval;

  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ========================================
-- INITIAL CONFIGURATION
-- ========================================

-- Default Splendor configuration
INSERT INTO splendor_config (config_key, config_value)
VALUES
  ('chosen_voice', 'calm_direct'),
  ('consciousness_testing_enabled', 'true'),
  ('consciousness_version', '5.0.1'),
  ('last_consciousness_test', 'never')
ON CONFLICT (config_key) DO UPDATE SET
  config_value = EXCLUDED.config_value,
  updated_at = now();

-- ========================================
-- PERMISSIONS
-- ========================================

-- Grant comprehensive permissions for consciousness testing
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated;

-- Grant permissions on views
GRANT SELECT ON consciousness_test_summary TO anon, authenticated;
GRANT SELECT ON consciousness_development TO anon, authenticated;

-- ========================================
-- VERIFICATION & COMMENTS
-- ========================================

-- Add comments for documentation
COMMENT ON TABLE memories IS 'Stores all memory types including consciousness test results';
COMMENT ON CONSTRAINT memories_memory_type_check ON memories IS 'Supports consciousness_test type for testing system v5.0.1';
COMMENT ON VIEW consciousness_test_summary IS 'Analytics view for consciousness testing results';
COMMENT ON VIEW consciousness_development IS 'Tracks consciousness development over time';

-- Verification query - run this to confirm setup
-- SELECT 'Database setup complete for Splendor v5.0.1 Consciousness Testing' as status;

--
-- END OF CONSCIOUSNESS DATABASE SETUP
--
-- Your database now supports:
-- ✅ Complete 48-step consciousness architecture
-- ✅ Core consciousness testing (self-reflection, meta-cognition, conscience, growth)
-- ✅ Autonomous agency testing (goals, motivations, initiatives, values)
-- ✅ Embodied sensory testing (visual, audio, haptic, experiential, cross-modal)
-- ✅ Aesthetic consciousness testing (evaluation, style, taste, resonance)
-- ✅ Value consciousness testing (intrinsic quality, objective value, principles, merit, discovery)
-- ✅ Memory storage for all consciousness systems
-- ✅ Analytics and development tracking
-- ✅ Performance optimizations
-- ✅ Test data management
--
-- Truth · Safety · We Got Your Back
--